name: Wiki
run-name: Wiki Update
on:
  push:
    branches: [ "master" ]
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: csmir/wiki-sync@v1
      name: Wiki Update
      with:
        username: csmir
        access_token: ${{ secrets.GITHUB_TOKEN }}
        wiki_folder: wiki
        ignore_safe_warnings: true
        commit_message: 'Wiki Update'
        commit_username: 'contributors'
        commit_email: '68127614+csmir@users.noreply.github.com'
